//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Security;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("ru-RU" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("Standart Object Library")]
[assembly: AssemblyCompanyAttribute("Nur Telecom")]
[assembly: AssemblyProductAttribute("Dashboard")]
[assembly: AssemblyVersionAttribute("1.0.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.0.0")]
